dotenv: .env
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
wallets:
  from_key: ${PRIVATE_KEY}
  networks:
    default: development  
    